### ISSUE TITLE
Gauge Crashes after Update 1.0

### ISSUE THREAD

**Issue by KyriakosCY** [Billiam/pygauge#1]
Since the game exited Steam Early Access and was update to version 1.0 the gauge exits as soon as the telemetry starts once the stage is loaded. I managed to grab a shot of the output message but I have no Idea how to fix this. Any help will be greatly appreciated :)

![photo 19-12-2015 12 17 49](https://cloud.githubusercontent.com/assets/16360806/11912588/fad3d9ec-a64b-11e5-83d2-606b9ab822cb.png)

**Comment by Billiam** [comment]
Thanks for reporting the issue! I'm having some trouble reproducing it, though. 

I can see that the hardware settings xml format has changed since early access. Can you provide your current motion_platform settings?

My settings look like this:

``` xml
<motion_platform>
  <dbox enabled="true" />
  <udp enabled="true" extradata="3" ip="127.0.0.1" port="20777" delay="1" />
  <fanatec enabled="true" pedalVibrationScale="1.0" wheelVibrationScale="1.0" ledTrueForGearsFalseForSpeed="true" />
</motion_platform>
```

Right now, I'm able to hop into a custom rally event and receive telemetry data.

**Comment by KyriakosCY** [comment]
Hi,

Thanks for the reply. Your XML helped me solve my problem :) Before the update I was able to use extradata="2" with both your gauge.exe and x-sim but now since 1.0 it does not work. My xml is exactly the same as yours other than the extradata="3" part. I changed it to 2 and it now works.. But its strange that 3 worked before the update..

Thanks
